// generated by go run internal/gen.go -naturalType complex128; DO NOT EDIT.

// Copyright (c) 2018, Bruno M V Souza <github@b.bmvs.io>. All rights reserved.
// Use of this source code is governed by a BSD-2-Clause license that can be
// found in the LICENSE file.

package orderedmap

import "sync"

// NewComplex128Map return a new Map implemented by Complex128Map
func NewComplex128Map() *Complex128Map {
	return &Complex128Map{
		store: map[complex128]interface{}{},
		keys:  []complex128{},
	}
}

// Complex128Map insertion ordered Map implementation
type Complex128Map struct {
	sync.Mutex

	store map[complex128]interface{}
	keys  []complex128
}

// Put add a key-value pair to the Complex128Map
func (m *Complex128Map) Put(key complex128, value interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		m.keys = append(m.keys, key)
	}

	m.store[key] = value
}

// Get return the value of a key from the Complex128Map
func (m *Complex128Map) Get(key complex128) (value interface{}, found bool) {
	m.Lock()
	defer m.Unlock()

	value, found = m.store[key]
	return
}

// Remove remove a key-value pair from the Complex128Map
func (m *Complex128Map) Remove(key complex128) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		return
	}

	delete(m.store, key)

	for i, _ := range m.keys {
		if m.keys[i] == key {
			m.keys = append(m.keys[:i], m.keys[i+1:]...)
			break
		}
	}
}

// Empty return if the Complex128Map in empty or not
func (m *Complex128Map) Empty() bool {
	m.Lock()
	defer m.Unlock()

	return len(m.store) == 0
}

// Keys return the keys of the Complex128Map in insertion order
func (m *Complex128Map) Keys() []complex128 {
	m.Lock()
	defer m.Unlock()

	return m.keys
}

// Values return the values of the Complex128Map in insertion order
func (m *Complex128Map) Values() []interface{} {
	m.Lock()
	defer m.Unlock()

	values := make([]interface{}, len(m.store))
	for i, key := range m.keys {
		values[i] = m.store[key]
	}
	return values
}

// Size return the size of the Complex128Map
func (m *Complex128Map) Size() int {
	m.Lock()
	defer m.Unlock()

	return len(m.store)
}
