// generated by go run internal/gen.go -naturalType uint32; DO NOT EDIT.

// Copyright (c) 2018, Bruno M V Souza <github@b.bmvs.io>. All rights reserved.
// Use of this source code is governed by a BSD-2-Clause license that can be
// found in the LICENSE file.

package orderedmap

import "sync"

// NewUint32Map return a new Map implemented by Uint32Map
func NewUint32Map() *Uint32Map {
	return &Uint32Map{
		store: map[uint32]interface{}{},
		keys:  []uint32{},
	}
}

// Uint32Map insertion ordered Map implementation
type Uint32Map struct {
	sync.Mutex

	store map[uint32]interface{}
	keys  []uint32
}

// Put add a key-value pair to the Uint32Map
func (m *Uint32Map) Put(key uint32, value interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		m.keys = append(m.keys, key)
	}

	m.store[key] = value
}

// Get return the value of a key from the Uint32Map
func (m *Uint32Map) Get(key uint32) (value interface{}, found bool) {
	m.Lock()
	defer m.Unlock()

	value, found = m.store[key]
	return
}

// Remove remove a key-value pair from the Uint32Map
func (m *Uint32Map) Remove(key uint32) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		return
	}

	delete(m.store, key)

	for i, _ := range m.keys {
		if m.keys[i] == key {
			m.keys = append(m.keys[:i], m.keys[i+1:]...)
			break
		}
	}
}

// Empty return if the Uint32Map in empty or not
func (m *Uint32Map) Empty() bool {
	m.Lock()
	defer m.Unlock()

	return len(m.store) == 0
}

// Keys return the keys of the Uint32Map in insertion order
func (m *Uint32Map) Keys() []uint32 {
	m.Lock()
	defer m.Unlock()

	return m.keys
}

// Values return the values of the Uint32Map in insertion order
func (m *Uint32Map) Values() []interface{} {
	m.Lock()
	defer m.Unlock()

	values := make([]interface{}, len(m.store))
	for i, key := range m.keys {
		values[i] = m.store[key]
	}
	return values
}

// Size return the size of the Uint32Map
func (m *Uint32Map) Size() int {
	m.Lock()
	defer m.Unlock()

	return len(m.store)
}
