// generated by go run internal/gen.go -naturalType *float32; DO NOT EDIT.

// Copyright (c) 2018, Bruno M V Souza <github@b.bmvs.io>. All rights reserved.
// Use of this source code is governed by a BSD-2-Clause license that can be
// found in the LICENSE file.

package orderedmap

import "sync"

// NewFloat32PtrMap return a new Map implemented by Float32PtrMap
func NewFloat32PtrMap() *Float32PtrMap {
	return &Float32PtrMap{
		store: map[*float32]interface{}{},
		keys:  []*float32{},
	}
}

// Float32PtrMap insertion ordered Map implementation
type Float32PtrMap struct {
	sync.Mutex

	store map[*float32]interface{}
	keys  []*float32
}

// Put add a key-value pair to the Float32PtrMap
func (m *Float32PtrMap) Put(key *float32, value interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		m.keys = append(m.keys, key)
	}

	m.store[key] = value
}

// Get return the value of a key from the Float32PtrMap
func (m *Float32PtrMap) Get(key *float32) (value interface{}, found bool) {
	m.Lock()
	defer m.Unlock()

	value, found = m.store[key]
	return
}

// Remove remove a key-value pair from the Float32PtrMap
func (m *Float32PtrMap) Remove(key *float32) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		return
	}

	delete(m.store, key)

	for i, _ := range m.keys {
		if m.keys[i] == key {
			m.keys = append(m.keys[:i], m.keys[i+1:]...)
			break
		}
	}
}

// Empty return if the Float32PtrMap in empty or not
func (m *Float32PtrMap) Empty() bool {
	m.Lock()
	defer m.Unlock()

	return len(m.store) == 0
}

// Keys return the keys of the Float32PtrMap in insertion order
func (m *Float32PtrMap) Keys() []*float32 {
	m.Lock()
	defer m.Unlock()

	return m.keys
}

// Values return the values of the Float32PtrMap in insertion order
func (m *Float32PtrMap) Values() []interface{} {
	m.Lock()
	defer m.Unlock()

	values := make([]interface{}, len(m.store))
	for i, key := range m.keys {
		values[i] = m.store[key]
	}
	return values
}

// Size return the size of the Float32PtrMap
func (m *Float32PtrMap) Size() int {
	m.Lock()
	defer m.Unlock()

	return len(m.store)
}
