// generated by go run internal/gen.go -naturalType *uint16; DO NOT EDIT.

// Copyright (c) 2018, Bruno M V Souza <github@b.bmvs.io>. All rights reserved.
// Use of this source code is governed by a BSD-2-Clause license that can be
// found in the LICENSE file.

package orderedmap

import "sync"

// NewUint16PtrMap return a new Map implemented by Uint16PtrMap
func NewUint16PtrMap() *Uint16PtrMap {
	return &Uint16PtrMap{
		store: map[*uint16]interface{}{},
		keys:  []*uint16{},
	}
}

// Uint16PtrMap insertion ordered Map implementation
type Uint16PtrMap struct {
	sync.Mutex

	store map[*uint16]interface{}
	keys  []*uint16
}

// Put add a key-value pair to the Uint16PtrMap
func (m *Uint16PtrMap) Put(key *uint16, value interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		m.keys = append(m.keys, key)
	}

	m.store[key] = value
}

// Get return the value of a key from the Uint16PtrMap
func (m *Uint16PtrMap) Get(key *uint16) (value interface{}, found bool) {
	m.Lock()
	defer m.Unlock()

	value, found = m.store[key]
	return
}

// Remove remove a key-value pair from the Uint16PtrMap
func (m *Uint16PtrMap) Remove(key *uint16) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		return
	}

	delete(m.store, key)

	for i, _ := range m.keys {
		if m.keys[i] == key {
			m.keys = append(m.keys[:i], m.keys[i+1:]...)
			break
		}
	}
}

// Empty return if the Uint16PtrMap in empty or not
func (m *Uint16PtrMap) Empty() bool {
	m.Lock()
	defer m.Unlock()

	return len(m.store) == 0
}

// Keys return the keys of the Uint16PtrMap in insertion order
func (m *Uint16PtrMap) Keys() []*uint16 {
	m.Lock()
	defer m.Unlock()

	return m.keys
}

// Values return the values of the Uint16PtrMap in insertion order
func (m *Uint16PtrMap) Values() []interface{} {
	m.Lock()
	defer m.Unlock()

	values := make([]interface{}, len(m.store))
	for i, key := range m.keys {
		values[i] = m.store[key]
	}
	return values
}

// Size return the size of the Uint16PtrMap
func (m *Uint16PtrMap) Size() int {
	m.Lock()
	defer m.Unlock()

	return len(m.store)
}
