// generated by go run internal/gen.go -naturalType int8; DO NOT EDIT.

// Copyright (c) 2018, Bruno M V Souza <github@b.bmvs.io>. All rights reserved.
// Use of this source code is governed by a BSD-2-Clause license that can be
// found in the LICENSE file.

package orderedmap

import "sync"

// NewInt8Map return a new Map implemented by Int8Map
func NewInt8Map() *Int8Map {
	return &Int8Map{
		store: map[int8]interface{}{},
		keys:  []int8{},
	}
}

// Int8Map insertion ordered Map implementation
type Int8Map struct {
	sync.Mutex

	store map[int8]interface{}
	keys  []int8
}

// Put add a key-value pair to the Int8Map
func (m *Int8Map) Put(key int8, value interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		m.keys = append(m.keys, key)
	}

	m.store[key] = value
}

// Get return the value of a key from the Int8Map
func (m *Int8Map) Get(key int8) (value interface{}, found bool) {
	m.Lock()
	defer m.Unlock()

	value, found = m.store[key]
	return
}

// Remove remove a key-value pair from the Int8Map
func (m *Int8Map) Remove(key int8) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		return
	}

	delete(m.store, key)

	for i, _ := range m.keys {
		if m.keys[i] == key {
			m.keys = append(m.keys[:i], m.keys[i+1:]...)
			break
		}
	}
}

// Empty return if the Int8Map in empty or not
func (m *Int8Map) Empty() bool {
	m.Lock()
	defer m.Unlock()

	return len(m.store) == 0
}

// Keys return the keys of the Int8Map in insertion order
func (m *Int8Map) Keys() []int8 {
	m.Lock()
	defer m.Unlock()

	return m.keys
}

// Values return the values of the Int8Map in insertion order
func (m *Int8Map) Values() []interface{} {
	m.Lock()
	defer m.Unlock()

	values := make([]interface{}, len(m.store))
	for i, key := range m.keys {
		values[i] = m.store[key]
	}
	return values
}

// Size return the size of the Int8Map
func (m *Int8Map) Size() int {
	m.Lock()
	defer m.Unlock()

	return len(m.store)
}
