// generated by go run internal/gen.go -naturalType *uintptr; DO NOT EDIT.

// Copyright (c) 2018, Bruno M V Souza <github@b.bmvs.io>. All rights reserved.
// Use of this source code is governed by a BSD-2-Clause license that can be
// found in the LICENSE file.

package orderedmap

import "sync"

// NewUintptrPtrMap return a new Map implemented by UintptrPtrMap
func NewUintptrPtrMap() *UintptrPtrMap {
	return &UintptrPtrMap{
		store: map[*uintptr]interface{}{},
		keys:  []*uintptr{},
	}
}

// UintptrPtrMap insertion ordered Map implementation
type UintptrPtrMap struct {
	sync.Mutex

	store map[*uintptr]interface{}
	keys  []*uintptr
}

// Put add a key-value pair to the UintptrPtrMap
func (m *UintptrPtrMap) Put(key *uintptr, value interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		m.keys = append(m.keys, key)
	}

	m.store[key] = value
}

// Get return the value of a key from the UintptrPtrMap
func (m *UintptrPtrMap) Get(key *uintptr) (value interface{}, found bool) {
	m.Lock()
	defer m.Unlock()

	value, found = m.store[key]
	return
}

// Remove remove a key-value pair from the UintptrPtrMap
func (m *UintptrPtrMap) Remove(key *uintptr) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		return
	}

	delete(m.store, key)

	for i, _ := range m.keys {
		if m.keys[i] == key {
			m.keys = append(m.keys[:i], m.keys[i+1:]...)
			break
		}
	}
}

// Empty return if the UintptrPtrMap in empty or not
func (m *UintptrPtrMap) Empty() bool {
	m.Lock()
	defer m.Unlock()

	return len(m.store) == 0
}

// Keys return the keys of the UintptrPtrMap in insertion order
func (m *UintptrPtrMap) Keys() []*uintptr {
	m.Lock()
	defer m.Unlock()

	return m.keys
}

// Values return the values of the UintptrPtrMap in insertion order
func (m *UintptrPtrMap) Values() []interface{} {
	m.Lock()
	defer m.Unlock()

	values := make([]interface{}, len(m.store))
	for i, key := range m.keys {
		values[i] = m.store[key]
	}
	return values
}

// Size return the size of the UintptrPtrMap
func (m *UintptrPtrMap) Size() int {
	m.Lock()
	defer m.Unlock()

	return len(m.store)
}
