// generated by go run internal/gen.go -naturalType *complex64; DO NOT EDIT.

// Copyright (c) 2018, Bruno M V Souza <github@b.bmvs.io>. All rights reserved.
// Use of this source code is governed by a BSD-2-Clause license that can be
// found in the LICENSE file.

package orderedmap

import "sync"

// NewComplex64PtrMap return a new Map implemented by Complex64PtrMap
func NewComplex64PtrMap() *Complex64PtrMap {
	return &Complex64PtrMap{
		store: map[*complex64]interface{}{},
		keys:  []*complex64{},
	}
}

// Complex64PtrMap insertion ordered Map implementation
type Complex64PtrMap struct {
	sync.Mutex

	store map[*complex64]interface{}
	keys  []*complex64
}

// Put add a key-value pair to the Complex64PtrMap
func (m *Complex64PtrMap) Put(key *complex64, value interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		m.keys = append(m.keys, key)
	}

	m.store[key] = value
}

// Get return the value of a key from the Complex64PtrMap
func (m *Complex64PtrMap) Get(key *complex64) (value interface{}, found bool) {
	m.Lock()
	defer m.Unlock()

	value, found = m.store[key]
	return
}

// Remove remove a key-value pair from the Complex64PtrMap
func (m *Complex64PtrMap) Remove(key *complex64) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		return
	}

	delete(m.store, key)

	for i, _ := range m.keys {
		if m.keys[i] == key {
			m.keys = append(m.keys[:i], m.keys[i+1:]...)
			break
		}
	}
}

// Empty return if the Complex64PtrMap in empty or not
func (m *Complex64PtrMap) Empty() bool {
	m.Lock()
	defer m.Unlock()

	return len(m.store) == 0
}

// Keys return the keys of the Complex64PtrMap in insertion order
func (m *Complex64PtrMap) Keys() []*complex64 {
	m.Lock()
	defer m.Unlock()

	return m.keys
}

// Values return the values of the Complex64PtrMap in insertion order
func (m *Complex64PtrMap) Values() []interface{} {
	m.Lock()
	defer m.Unlock()

	values := make([]interface{}, len(m.store))
	for i, key := range m.keys {
		values[i] = m.store[key]
	}
	return values
}

// Size return the size of the Complex64PtrMap
func (m *Complex64PtrMap) Size() int {
	m.Lock()
	defer m.Unlock()

	return len(m.store)
}
