// generated by go run internal/gen.go -naturalType interface{}; DO NOT EDIT.

// Copyright (c) 2018, Bruno M V Souza <github@b.bmvs.io>. All rights reserved.
// Use of this source code is governed by a BSD-2-Clause license that can be
// found in the LICENSE file.

package orderedmap

import "sync"

// New return a new Map implemented by GenericMap
func New() *GenericMap {
	return &GenericMap{
		store: map[interface{}]interface{}{},
		keys:  []interface{}{},
	}
}

// GenericMap insertion ordered Map implementation
type GenericMap struct {
	sync.Mutex

	store map[interface{}]interface{}
	keys  []interface{}
}

// Put add a key-value pair to the GenericMap
func (m *GenericMap) Put(key interface{}, value interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		m.keys = append(m.keys, key)
	}

	m.store[key] = value
}

// Get return the value of a key from the GenericMap
func (m *GenericMap) Get(key interface{}) (value interface{}, found bool) {
	m.Lock()
	defer m.Unlock()

	value, found = m.store[key]
	return
}

// Remove remove a key-value pair from the GenericMap
func (m *GenericMap) Remove(key interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		return
	}

	delete(m.store, key)

	for i, _ := range m.keys {
		if m.keys[i] == key {
			m.keys = append(m.keys[:i], m.keys[i+1:]...)
			break
		}
	}
}

// Empty return if the GenericMap in empty or not
func (m *GenericMap) Empty() bool {
	m.Lock()
	defer m.Unlock()

	return len(m.store) == 0
}

// Keys return the keys of the GenericMap in insertion order
func (m *GenericMap) Keys() []interface{} {
	m.Lock()
	defer m.Unlock()

	return m.keys
}

// Values return the values of the GenericMap in insertion order
func (m *GenericMap) Values() []interface{} {
	m.Lock()
	defer m.Unlock()

	values := make([]interface{}, len(m.store))
	for i, key := range m.keys {
		values[i] = m.store[key]
	}
	return values
}

// Size return the size of the GenericMap
func (m *GenericMap) Size() int {
	m.Lock()
	defer m.Unlock()

	return len(m.store)
}
