// generated by go run internal/gen.go -naturalType *int; DO NOT EDIT.

// Copyright (c) 2018, Bruno M V Souza <github@b.bmvs.io>. All rights reserved.
// Use of this source code is governed by a BSD-2-Clause license that can be
// found in the LICENSE file.

package orderedmap

import "sync"

// NewIntPtrMap return a new Map implemented by IntPtrMap
func NewIntPtrMap() *IntPtrMap {
	return &IntPtrMap{
		store: map[*int]interface{}{},
		keys:  []*int{},
	}
}

// IntPtrMap insertion ordered Map implementation
type IntPtrMap struct {
	sync.Mutex

	store map[*int]interface{}
	keys  []*int
}

// Put add a key-value pair to the IntPtrMap
func (m *IntPtrMap) Put(key *int, value interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		m.keys = append(m.keys, key)
	}

	m.store[key] = value
}

// Get return the value of a key from the IntPtrMap
func (m *IntPtrMap) Get(key *int) (value interface{}, found bool) {
	m.Lock()
	defer m.Unlock()

	value, found = m.store[key]
	return
}

// Remove remove a key-value pair from the IntPtrMap
func (m *IntPtrMap) Remove(key *int) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		return
	}

	delete(m.store, key)

	for i, _ := range m.keys {
		if m.keys[i] == key {
			m.keys = append(m.keys[:i], m.keys[i+1:]...)
			break
		}
	}
}

// Empty return if the IntPtrMap in empty or not
func (m *IntPtrMap) Empty() bool {
	m.Lock()
	defer m.Unlock()

	return len(m.store) == 0
}

// Keys return the keys of the IntPtrMap in insertion order
func (m *IntPtrMap) Keys() []*int {
	m.Lock()
	defer m.Unlock()

	return m.keys
}

// Values return the values of the IntPtrMap in insertion order
func (m *IntPtrMap) Values() []interface{} {
	m.Lock()
	defer m.Unlock()

	values := make([]interface{}, len(m.store))
	for i, key := range m.keys {
		values[i] = m.store[key]
	}
	return values
}

// Size return the size of the IntPtrMap
func (m *IntPtrMap) Size() int {
	m.Lock()
	defer m.Unlock()

	return len(m.store)
}
