// generated by go run internal/gen.go -naturalType rune; DO NOT EDIT.

// Copyright (c) 2018, Bruno M V Souza <github@b.bmvs.io>. All rights reserved.
// Use of this source code is governed by a BSD-2-Clause license that can be
// found in the LICENSE file.

package orderedmap

import "sync"

// NewRuneMap return a new Map implemented by RuneMap
func NewRuneMap() *RuneMap {
	return &RuneMap{
		store: map[rune]interface{}{},
		keys:  []rune{},
	}
}

// RuneMap insertion ordered Map implementation
type RuneMap struct {
	sync.Mutex

	store map[rune]interface{}
	keys  []rune
}

// Put add a key-value pair to the RuneMap
func (m *RuneMap) Put(key rune, value interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		m.keys = append(m.keys, key)
	}

	m.store[key] = value
}

// Get return the value of a key from the RuneMap
func (m *RuneMap) Get(key rune) (value interface{}, found bool) {
	m.Lock()
	defer m.Unlock()

	value, found = m.store[key]
	return
}

// Remove remove a key-value pair from the RuneMap
func (m *RuneMap) Remove(key rune) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		return
	}

	delete(m.store, key)

	for i, _ := range m.keys {
		if m.keys[i] == key {
			m.keys = append(m.keys[:i], m.keys[i+1:]...)
			break
		}
	}
}

// Empty return if the RuneMap in empty or not
func (m *RuneMap) Empty() bool {
	m.Lock()
	defer m.Unlock()

	return len(m.store) == 0
}

// Keys return the keys of the RuneMap in insertion order
func (m *RuneMap) Keys() []rune {
	m.Lock()
	defer m.Unlock()

	return m.keys
}

// Values return the values of the RuneMap in insertion order
func (m *RuneMap) Values() []interface{} {
	m.Lock()
	defer m.Unlock()

	values := make([]interface{}, len(m.store))
	for i, key := range m.keys {
		values[i] = m.store[key]
	}
	return values
}

// Size return the size of the RuneMap
func (m *RuneMap) Size() int {
	m.Lock()
	defer m.Unlock()

	return len(m.store)
}
