// generated by go run internal/gen.go -naturalType *int16; DO NOT EDIT.

// Copyright (c) 2018, Bruno M V Souza <github@b.bmvs.io>. All rights reserved.
// Use of this source code is governed by a BSD-2-Clause license that can be
// found in the LICENSE file.

package orderedmap

import "sync"

// NewInt16PtrMap return a new Map implemented by Int16PtrMap
func NewInt16PtrMap() *Int16PtrMap {
	return &Int16PtrMap{
		store: map[*int16]interface{}{},
		keys:  []*int16{},
	}
}

// Int16PtrMap insertion ordered Map implementation
type Int16PtrMap struct {
	sync.Mutex

	store map[*int16]interface{}
	keys  []*int16
}

// Put add a key-value pair to the Int16PtrMap
func (m *Int16PtrMap) Put(key *int16, value interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		m.keys = append(m.keys, key)
	}

	m.store[key] = value
}

// Get return the value of a key from the Int16PtrMap
func (m *Int16PtrMap) Get(key *int16) (value interface{}, found bool) {
	m.Lock()
	defer m.Unlock()

	value, found = m.store[key]
	return
}

// Remove remove a key-value pair from the Int16PtrMap
func (m *Int16PtrMap) Remove(key *int16) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		return
	}

	delete(m.store, key)

	for i, _ := range m.keys {
		if m.keys[i] == key {
			m.keys = append(m.keys[:i], m.keys[i+1:]...)
			break
		}
	}
}

// Empty return if the Int16PtrMap in empty or not
func (m *Int16PtrMap) Empty() bool {
	m.Lock()
	defer m.Unlock()

	return len(m.store) == 0
}

// Keys return the keys of the Int16PtrMap in insertion order
func (m *Int16PtrMap) Keys() []*int16 {
	m.Lock()
	defer m.Unlock()

	return m.keys
}

// Values return the values of the Int16PtrMap in insertion order
func (m *Int16PtrMap) Values() []interface{} {
	m.Lock()
	defer m.Unlock()

	values := make([]interface{}, len(m.store))
	for i, key := range m.keys {
		values[i] = m.store[key]
	}
	return values
}

// Size return the size of the Int16PtrMap
func (m *Int16PtrMap) Size() int {
	m.Lock()
	defer m.Unlock()

	return len(m.store)
}
