// generated by go run internal/gen.go -naturalType float32; DO NOT EDIT.

// Copyright (c) 2018, Bruno M V Souza <github@b.bmvs.io>. All rights reserved.
// Use of this source code is governed by a BSD-2-Clause license that can be
// found in the LICENSE file.

package orderedmap

import "sync"

// NewFloat32Map return a new Map implemented by Float32Map
func NewFloat32Map() *Float32Map {
	return &Float32Map{
		store: map[float32]interface{}{},
		keys:  []float32{},
	}
}

// Float32Map insertion ordered Map implementation
type Float32Map struct {
	sync.Mutex

	store map[float32]interface{}
	keys  []float32
}

// Put add a key-value pair to the Float32Map
func (m *Float32Map) Put(key float32, value interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		m.keys = append(m.keys, key)
	}

	m.store[key] = value
}

// Get return the value of a key from the Float32Map
func (m *Float32Map) Get(key float32) (value interface{}, found bool) {
	m.Lock()
	defer m.Unlock()

	value, found = m.store[key]
	return
}

// Remove remove a key-value pair from the Float32Map
func (m *Float32Map) Remove(key float32) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		return
	}

	delete(m.store, key)

	for i, _ := range m.keys {
		if m.keys[i] == key {
			m.keys = append(m.keys[:i], m.keys[i+1:]...)
			break
		}
	}
}

// Empty return if the Float32Map in empty or not
func (m *Float32Map) Empty() bool {
	m.Lock()
	defer m.Unlock()

	return len(m.store) == 0
}

// Keys return the keys of the Float32Map in insertion order
func (m *Float32Map) Keys() []float32 {
	m.Lock()
	defer m.Unlock()

	return m.keys
}

// Values return the values of the Float32Map in insertion order
func (m *Float32Map) Values() []interface{} {
	m.Lock()
	defer m.Unlock()

	values := make([]interface{}, len(m.store))
	for i, key := range m.keys {
		values[i] = m.store[key]
	}
	return values
}

// Size return the size of the Float32Map
func (m *Float32Map) Size() int {
	m.Lock()
	defer m.Unlock()

	return len(m.store)
}
