// generated by go run internal/gen.go -naturalType {{.NaturalType}}; DO NOT EDIT.

// Copyright (c) 2018, Bruno M V Souza <github@b.bmvs.io>. All rights reserved.
// Use of this source code is governed by a BSD-2-Clause license that can be
// found in the LICENSE file.

package orderedmap

import "sync"

{{if .Generic}}// New return a new Map implemented by {{.TypeName}}
func New() *{{.TypeName}} {
{{else}}// New{{.TypeName}} return a new Map implemented by {{.TypeName}}
func New{{.TypeName}}() *{{.TypeName}} {
{{end}}	return &{{.TypeName}}{
		store: map[{{.NaturalType}}]interface{}{},
		keys:  []{{.NaturalType}}{},
	}
}

// {{.TypeName}} insertion ordered Map implementation
type {{.TypeName}} struct {
	sync.Mutex

	store map[{{.NaturalType}}]interface{}
	keys  []{{.NaturalType}}
}

// Put add a key-value pair to the {{.TypeName}}
func (m *{{.TypeName}}) Put(key {{.NaturalType}}, value interface{}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		m.keys = append(m.keys, key)
	}

	m.store[key] = value
}

// Get return the value of a key from the {{.TypeName}}
func (m *{{.TypeName}}) Get(key {{.NaturalType}}) (value interface{}, found bool) {
	m.Lock()
	defer m.Unlock()

	value, found = m.store[key]
	return
}

// Remove remove a key-value pair from the {{.TypeName}}
func (m *{{.TypeName}}) Remove(key {{.NaturalType}}) {
	m.Lock()
	defer m.Unlock()

	if _, found := m.store[key]; !found {
		return
	}

	delete(m.store, key)

	for i, _ := range m.keys {
		if m.keys[i] == key {
			m.keys = append(m.keys[:i], m.keys[i+1:]...)
			break
		}
	}
}

// Empty return if the {{.TypeName}} in empty or not
func (m *{{.TypeName}}) Empty() bool {
	m.Lock()
	defer m.Unlock()

	return len(m.store) == 0
}

// Keys return the keys of the {{.TypeName}} in insertion order
func (m *{{.TypeName}}) Keys() []{{.NaturalType}} {
	m.Lock()
	defer m.Unlock()

	return m.keys
}

// Values return the values of the {{.TypeName}} in insertion order
func (m *{{.TypeName}}) Values() []interface{} {
	m.Lock()
	defer m.Unlock()

	values := make([]interface{}, len(m.store))
	for i, key := range m.keys {
		values[i] = m.store[key]
	}
	return values
}

// Size return the size of the {{.TypeName}}
func (m *{{.TypeName}}) Size() int {
	m.Lock()
	defer m.Unlock()

	return len(m.store)
}
